Implemented flask api for user CRUD requests
iManapov/ru-study-python pull request #4
Opened 2023-04-19 08:23 UTC by iManapov

2023-04-19 17:44 UTC, aleksandr-semenov-dbp requested changes

2023-04-19 17:44 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +                }, HTTPStatus.NOT_FOUND
Давай реализуем 404 и в patch и delete

2023-04-20 06:25 UTC, iManapov commented on flask_exercises/flask_excercises.py
> +                }, HTTPStatus.NOT_FOUND
Добавил 404 ошибки в коммите 9de52e453db73e294ab81026e4d6241f1b4c511e

2023-04-20 12:17 UTC, aleksandr-semenov-dbp approved these changes

2023-04-20 12:42 UTC, merged